/*
 * Parser of .vcd files generated by rtl_433, intended to extract specific signal timing
 * for re-transmission purposes.
 * 
 * 
 * Copyright (C) 2018 by Peter Drozda
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 
#ifndef PARSER_H
#define PARSER_H

typedef struct vc {
    long time;
    int value;
    struct vc* next;
} vct;

/* 
 * Parses the provided .vcd file, extracting timing and values for signal
 * identified by signalIdentifier.
 * 
 * @param fileName VCD file generated by rtl_433
 * @param signalIdentifier identifier of the signal to be extracted from .vcd
 * 
 */
vct* parseVCDFile(char* fileName, char signalIdentifier);

/*
 * Iterates the result of parser and executes callback function on each entry.
 * Callback function should return 0 if finished successfuly and any other value on error in
 * order to break the iteration and return the error code immediately.
 * 
 * @param resultList the result of the parser
 * @param callback the callback function to be executed on each entry
 */
int handleResult(vct* resultList, int (*callback)(long, int));

#endif
