/*
 * Parser of .vcd files generated by rtl_433, intended to extract specific signal timing
 * for re-transmission purposes.
 * 
 * 
 * Copyright (C) 2018 by Peter Drozda
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 
#include <stdio.h>
#include <stdlib.h>
#include "parser.h"


static char* getValue(char* line, int index, char* result) {
	int i = 0;
	
	while(line[index] != ' ') {
		result[i++] = line[index--];
	}
	
	return result;
}

static vct* parseLine(char* line, char signalIdentifier) {
	char c = line[0];
	char time[12];
	char value[12];
	int timeIndex = 0;
	int lineIndex = 0;
	vct* result;

 	if(c == '#') {
		do {
			if(c == signalIdentifier) {
				result = malloc(sizeof(vct));
				result->time = strtol(time, NULL, 10);
				result->value = atoi(getValue(line, lineIndex-1, value));
				result->next = NULL;
				
				return result;
			}
			c = line[++lineIndex];
			if(timeIndex != -1) {
				if(c != ' ') {
					time[timeIndex++] = c;
				} else {
					time[timeIndex] = '\0';
					timeIndex = -1;
				}
			}
		} while(c!='\0');
	}
	
	return NULL;
}

static FILE* openFile(char* fileName) {
	FILE *fp;
	fp = fopen(fileName, "r");
	
	if (fp == NULL) {
		perror("Error opening the file.\n");
		exit(EXIT_FAILURE);
	}
	
	return fp;
}

int handleResult(vct* resultList, int (*callback)(long, int)) {
	vct* purge;
	int result = 0;
	
	while(resultList != NULL) {
		result = (*callback)(resultList->time, resultList->value);
		if(result != 0) {
			return result;
		}
		purge = resultList;
		resultList = resultList->next;
		free(purge);
	}
	
	return result;
}

vct* parseVCDFile(char* fileName, char signalIdentifier) {
	FILE *fp = openFile(fileName);
	char line[100];
	vct* resultList = NULL;
	vct* next = NULL;

	printf("Parsing vcd file:%s, looking for signal:%c\n", fileName, signalIdentifier);
	while ((fgets(line, sizeof(line), fp) != NULL) && (resultList == NULL)){
		next = parseLine(line, signalIdentifier);
		if(next != NULL) {
			resultList = next;
		}
	}
	
	while (fgets(line, sizeof(line), fp) != NULL){
		next->next = parseLine(line, signalIdentifier);
		if(next->next != NULL) {
			next = next->next;
		}
	}
	fclose(fp);
	
	return resultList;
}
